apiVersion: v1
kind: PersistentVolume
metadata: 
  name: clearml-cache-pv
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath: 
    path: /mnt/fedvol/apps/clearml-enterprise/clearml-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clearml-cache-pvc
  namespace: clearml-agent
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
