apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clearmlAgent.fullname" . }}-pt
data:
  template.yaml: |
    {{- if .Values.agentk8sglue.taskAsJob }}
    {{ include "taskContainer.jobTemplate" . | nindent 4}}
    {{- else }}
    {{ include "taskContainer.podTemplate" . | nindent 4}}
    {{- end }}
  secrets.yaml: |
    {{- range $key, $value := $.Values.agentk8sglue.queues }}
    {{ $key }}:
      {{- if $value.templateOverrides.fileMounts }}
        - {{ include "clearmlAgent.fullname" $ }}-{{ $key }}-fm
      {{- else if $.Values.agentk8sglue.basePodTemplate.fileMounts }}
        - {{ include "clearmlAgent.fullname" $ }}-fm
      {{- end }}
    {{- end }}
{{- if .Values.sessions.portModeEnabled }}
{{- range untilStep 1 ( ( add .Values.sessions.maxServices 1 ) | int ) 1 }}
  services-{{ . }}.yaml: |
    apiVersion: v1
    kind: Service
    metadata:
      name: clearml-session-{{ . }}
      labels:
        {{- include "clearmlAgent.labels" $ | nindent 8 }}
      {{- with $.Values.sessions.svcAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      type: {{ $.Values.sessions.svcType }}
      ports:
        - targetPort: 10022
          {{- if eq $.Values.sessions.svcType "NodePort" }}
          port: 10022
          {{- else }}
          port: {{ add $.Values.sessions.startingPort . }}
          {{- end }}
          protocol: TCP
          {{- if eq $.Values.sessions.svcType "NodePort" }}
          nodePort: {{ add $.Values.sessions.startingPort . }}
          {{- end }}
      selector:
        ai.allegro.agent.serial: pod-{{ . }}
{{- end }}
{{- end }}
